---
# Variable use for all Ansible groups
join_command: "{{vault_join_command}}"
ec2_access_key: "{{vault_ec2_access_key}}"
ec2_secret_key: "{{vault_ec2_secret_key}}"
ec2_keypair: "aa-keypair"
ec2_region: "us-west-1"
